Buffet/Models/Restaurant.cs
using System;
using System.Collections.Generic;

namespace Buffet.Models;

public partial class Restaurant
{
    public string ResId { get; set; } = null!;

    public string ResName { get; set; } = null!;

    public string ResPhone { get; set; } = null!;

    public string ResLocation { get; set; } = null!;

    public string ResAvg { get; set; } = null!;

    public string TypeId { get; set; } = null!;

    public string ResDtl { get; set; } = null!;

    public string TablesetIds { get; set; } = null!;

    public string? ResImg { get; set; }
}

Buffet/Models/RestaurantsType.cs
using System;
using System.Collections.Generic;

namespace Buffet.Models;

public partial class RestaurantsType
{
    public string TypeId { get; set; } = null!;

    public string TypeName { get; set; } = null!;
}

Buffet/Controllers/RestaurantController.cs
using Buffet.ViewModels;
using Buffet.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Buffet.Controllers
{
    public class RestaurantController : Controller
    {
        public readonly BuffetContext _db;
        public RestaurantController(BuffetContext db) { _db = db; }


        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("DutyId") != "staff" && HttpContext.Session.GetString("DutyId") != "admin")
            {
                TempData["ErrorMessage"] = "ไม่มีสิทธิใช้งาน";
                return RedirectToAction("Index", "Home");
            }
            var pdvm = from i in _db.Restaurants

                       select new Pdvm
                       {
                           ResId = i.ResId,
                           ResName = i.ResName,
                           ResPhone = i.ResPhone,
                           ResAvg = i.ResAvg,
                           ResLocation = i.ResLocation,
                           ResDtl = i.ResDtl
                       };

            //ถ้าค่าที่อ่านได้เป็น Null ก็ Return เรียก Function NorFound()
            if (pdvm == null) return NotFound();

            ViewBag.ErrorMessage = TempData["ErrorMessage"];
            //ถ้าพบ ส่ง Obj pd ที่ได้ให้ View ไปแสดง
            return View(pdvm);
        }
        public IActionResult EditCourse(int id)
        {
            if (HttpContext.Session.GetString("DutyId") != "staff" && HttpContext.Session.GetString("DutyId") != "admin")
            {
                TempData["ErrorMessage"] = "ไม่มีสิทธิใช้งาน";
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                TempData["ErrorMessage"] = "ระบุ ID";
                return RedirectToAction("Index");
            }
            var obj = _db.Courses.Find(id);
            if (obj == null)
            {
                TempData["ErrorMessage"] = "ไม่พบ ID";
                return RedirectToAction("Index");
            }
            ViewData["Res"] = new SelectList(_db.Restaurants, "ResId", "ResName");
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCourse(Course obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Courses.Update(obj);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorMessage = "ฐานข้อมูลไม่พร้อมทำงาน";
                    return NotFound();
                }

            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View(obj);
            }

        }

        public IActionResult EditSet(int id)
        {
            if (HttpContext.Session.GetString("DutyId") != "staff" && HttpContext.Session.GetString("DutyId") != "admin")
            {
                TempData["ErrorMessage"] = "ไม่มีสิทธิใช้งาน";
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                TempData["ErrorMessage"] = "ระบุ ID";
                return RedirectToAction("Index");
            }
            var obj = _db.Tablesets.Find(id);
            if (obj == null)
            {
                TempData["ErrorMessage"] = "ไม่พบ ID";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditSet(Tableset obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Tablesets.Update(obj);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorMessage = "ฐานข้อมูลไม่พร้อมทำงาน";
                    return View(obj);
                }

            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View(obj);
            }

        }

        public IActionResult EditResType(string id)
        {
            if (HttpContext.Session.GetString("DutyId") != "staff" && HttpContext.Session.GetString("DutyId") != "admin")
            {
                TempData["ErrorMessage"] = "ไม่มีสิทธิใช้งาน";
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                TempData["ErrorMessage"] = "ระบุ ID";
                return RedirectToAction("Index");
            }
            var obj = _db.RestaurantsTypes.Find(id);
            if (obj == null)
            {
                TempData["ErrorMessage"] = "ไม่พบ ID";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditResType(RestaurantsType obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.RestaurantsTypes.Update(obj);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorMessage = "ฐานข้อมูลไม่พร้อมทำงาน";
                    return View(obj);
                }

            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View(obj);
            }

        }
        public IActionResult CourseImgUpload(IFormFile imgfiles, int id)
        {
            var FileName = id;
            var FileExtension = Path.GetExtension(imgfiles.FileName);
            var SaveFilename = FileName + FileExtension;
            var SavePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\imgcourse");
            var SaveFilePath = Path.Combine(SavePath, SaveFilename);
            using (FileStream fs = System.IO.File.Create(SaveFilePath))
            {
                imgfiles.CopyTo(fs);
                fs.Flush();
            }

            var obj = _db.Courses.Find(id);
            if (obj != null)
            {
                obj.CourseImg = SaveFilename;
                _db.SaveChanges();
            }
            return RedirectToAction("Index", "Staff");

        }

        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("DutyId") != "staff" && HttpContext.Session.GetString("DutyId") != "admin")
            {
                TempData["ErrorMessage"] = "ไม่มีสิทธิใช้งาน";
                return RedirectToAction("Index", "Home");
            }


            ViewData["Type"] = new SelectList(_db.RestaurantsTypes, "TypeId", "TypeName");
            ViewData["Course"] = new SelectList(_db.Courses, "CourseId", "CourseName");
            ViewData["Set"] = new SelectList(_db.Tablesets, "TablesetIds", "Total");

            return View();


        }

        public IActionResult CreateCourse()
        {
            if (HttpContext.Session.GetString("DutyId") != "staff" && HttpContext.Session.GetString("DutyId") != "admin")
            {
                TempData["ErrorMessage"] = "ไม่มีสิทธิใช้งาน";
                return RedirectToAction("Index", "Home");
            }
            //ViewData["Type"] = new SelectList(_db.RestaurantsTypes, "TypeId", "TypeName");
            ViewData["name"] = new SelectList(_db.Restaurants, "ResId", "ResName");
            return View();
        }
        public IActionResult CreateTablesets()
        {
            if (HttpContext.Session.GetString("DutyId") != "staff" && HttpContext.Session.GetString("DutyId") != "admin")
            {
                TempData["ErrorMessage"] = "ไม่มีสิทธิใช้งาน";
                return RedirectToAction("Index", "Home");
            }

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateTablesets(Tableset obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var CourseIdCount = (from course in _db.Tablesets select course).Count();
                    var CourseId = CourseIdCount + 1;
                    var Total = "S=" + obj.Ssize + " M=" + obj.Msize + " L=" + obj.Lsize;
                    obj.TablesetIds = CourseId;
                    obj.Total = Total;
                    _db.Tablesets.Add(obj);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View(obj);
            }
            ViewBag.ErrorMessage = "การบันทึกผิดพลาด";
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Restaurant obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var ResIdCount = (from res in _db.Restaurants select res).Count();
                    var ResId = ResIdCount + 1;
                    string ResIds = ResId.ToString();
                    obj.ResId = ResIds;
                    _db.Restaurants.Add(obj);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View(obj);
            }
            ViewBag.ErrorMessage = "การบันทึกผิดพลาด";
            return View(obj);
        }

        [HttpPost]

Buffet/Views/Restaurant/CourseList.cshtml
@model IEnumerable<Buffet.ViewModels.Pdvm>
@{
    var stext = ViewBag.theText;
}
@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.ErrorMesage;
    </div>
}

<div class="container pt-5 mt-5">
    <div class="row">
        <div class="col-sm-6 col-md-8 col-lg-9">
            <a class="btn btn-primary" asp-action="Index">
                <i class=""></i>Restaurant
            </a>
            <a class="btn btn-primary" asp-action="CourseList">
                <i class=""></i>Course
            </a>
            <a class="btn btn-primary" asp-action="SetList">
                <i class=""></i>Set
            </a>
            <a class="btn btn-primary" asp-action="TypeList">
                <i class=""></i>Type
            </a>
        </div>
    </div>
</div>
<div class="container pt-3 mt-5">
    <form asp-controller="Restaurant" asp-action="Index">
        <div class="row">
            <div class="col-sm-6 col-md-8 col-lg-9">
                <a class="btn btn-primary" asp-action="Create">
                    <i class="bg-info bi-plus-lg"></i>เพิ่มร้านอาหาร
                </a>
                <a class="btn btn-primary" asp-action="CreateCourse">
                    <i class="bg-info bi-plus-lg"></i>เพิ่มCourse
                </a>
                <a class="btn btn-primary" asp-action="CreateTablesets">
                    <i class="bg-info bi-plus-lg"></i>เพิ่มชุดโต๊ะ
                </a>
                <a class="btn btn-primary" asp-action="CreateResType">
                    <i class="bg-info bi-plus-lg"></i>เพิ่มประเภทของร้าน
                </a>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="input-group">
                    <span class="input-group-text">ค้นหา</span>
                    <input type="text" name="stext" class="form-control" value="@stext" />
                    <button type="submit" class="btn btn-secondary">OK</button>
                </div>
            </div>
        </div>


    </form>
    <table class="table">
        <tr>

            <th>รหัสCourse</th>
            <th>รหัสร้านอาหาร</th>
            <th>ชื่อCourse</th>
            <th>ราคา</th>
            <th>ประเภท</th>
            <th>รายละเอียด</th>

        </tr>

        @{
            //กำหนดค่าเพื่อให้นับค่าแสดงลำดับ
            var i = 0;
        }
        @foreach (var item in Model)
        {
            i++;
            //Razor page ใข้เครื่องหมาย @ หน้าตัวแปรที่ต้องการให้แสดงผล
            <tr>

                <td>@item.CourseId</td>
                <td>@item.ResId</td>
                <td>@item.CourseName</td>
                <td>@item.CoursePrice</td>
                <td>@item.CourseType</td>
                <td>@item.CourseDtl</td>

                <td>
                    <a asp-action="EditCourse" asp-route-id="@item.CourseId">Edit</a>
                </td>
                <td class="text-center">
                    <a asp-action="DeleteCourse" asp-route-id="@item.CourseId">Delete</a>
                </td>
            </tr>

        }
    </table>
</div>

Buffet/Views/Restaurant/Create.cshtml
@model Buffet.Models.Restaurant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<div class="container pt-2 mt-2">
    <h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="ResId" class="control-label"></label>
                <input asp-for="ResId" class="form-control" value="0"/>
                <span asp-validation-for="ResId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResName" class="control-label"></label>
                <input asp-for="ResName" class="form-control" />
                <span asp-validation-for="ResName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResPhone" class="control-label"></label>
                <input asp-for="ResPhone" class="form-control" />
                <span asp-validation-for="ResPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResLocation" class="control-label"></label>
                <input asp-for="ResLocation" class="form-control" />
                <span asp-validation-for="ResLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResAvg" class="control-label"></label>
                <input asp-for="ResAvg" class="form-control" />
                <span asp-validation-for="ResAvg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeId" class="control-label"></label>
                 <select asp-for="TypeId" class="form-select" asp-items="ViewBag.Type"></select>
                <span asp-validation-for="TypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResDtl" class="control-label"></label>
                <input asp-for="ResDtl" class="form-control" />
                <span asp-validation-for="ResDtl" class="text-danger"></span>
            </div>
    
            <div class="form-group">
                <label asp-for="TablesetIds" class="control-label"></label>
                    <select asp-for="TablesetIds" class="form-select" asp-items="ViewBag.Set")></select>
                <span asp-validation-for="TablesetIds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Buffet/Views/Restaurant/CreateCourse.cshtml
@model Buffet.Models.Course

@{
    ViewData["Title"] = "CreateCourse";
}

<h1>CreateCourse</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateCourse">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="CourseId" class="control-label"></label>
                <input asp-for="CourseId" class="form-control" value="0" />
                <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseName" class="control-label"></label>
                <input asp-for="CourseName" class="form-control" />
                <span asp-validation-for="CourseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoursePrice" class="control-label"></label>
                <input asp-for="CoursePrice" class="form-control" />
                <span asp-validation-for="CoursePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseType" class="control-label"></label>
                <input asp-for="CourseType" class="form-control" />
                <span asp-validation-for="CourseType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseDtl" class="control-label"></label>
                <input asp-for="CourseDtl" class="form-control" />
                <span asp-validation-for="CourseDtl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResId" class="control-label"></label>
                <select asp-for="ResId" class="form-select" asp-items="ViewBag.name"></select>
                <span asp-validation-for="ResId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Buffet/Views/Restaurant/DeleteSet.cshtml
@model Buffet.Models.Tableset

@{
    ViewData["Title"] = "DeleteSet";
}

<h1>DeleteSet</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tableset</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            โต๊ะขนาด @Html.DisplayNameFor(model => model.Ssize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ssize)
        </dd>
        <dt class = "col-sm-2">
            โต๊ะขนาด @Html.DisplayNameFor(model => model.Msize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Msize)
        </dd>
        <dt class = "col-sm-2">
            โต๊ะขนาด @Html.DisplayNameFor(model => model.Lsize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lsize)
        </dd>
        <dt class = "col-sm-2">
            ทั้งหมด 
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
    </dl>
    
    <form asp-action="DeletePostSet">
        <input type="hidden" asp-for="TablesetIds" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Buffet/Views/Restaurant/Index.cshtml
@model IEnumerable<Buffet.ViewModels.Pdvm>
@{
    var stext = ViewBag.theText;
}
@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.ErrorMesage;
    </div>
}


<div class="container pt-5 mt-5">
    <div class="row">
        <div class="col-sm-6 col-md-8 col-lg-9">
            <a class="btn btn-primary" asp-action="Index" >
                <i class=""></i>Restaurant
            </a>
            <a class="btn btn-primary" asp-action="CourseList" >
                <i class=""></i>Course
            </a>
            <a class="btn btn-primary" asp-action="SetList">
                <i class=""></i>Set
            </a>
            <a class="btn btn-primary" asp-action="TypeList">
                <i class=""></i>Type
            </a>
        </div>
    </div>
    </div>
<div class="container pt-3 mt-5">
    <form asp-controller="Restaurant" asp-action="Index">
        <div class="row">
            <div class="col-sm-6 col-md-8 col-lg-9">
                <a class="btn btn-primary" asp-action="Create" >
                    <i class="bg-info bi-plus-lg"></i>เพิ่มร้านอาหาร
                </a>
                <a class="btn btn-primary" asp-action="CreateCourse">
                    <i class="bg-info bi-plus-lg"></i>เพิ่มCourse
                </a>
                <a class="btn btn-primary" asp-action="CreateTablesets">
                    <i class="bg-info bi-plus-lg"></i>เพิ่มชุดโต๊ะ
                </a>
                <a class="btn btn-primary" asp-action="CreateResType">
                    <i class="bg-info bi-plus-lg"></i>เพิ่มประเภทของร้าน
                </a>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="input-group">
                    <span class="input-group-text">ค้นหา</span>
                    <input type="text" name="stext" class="form-control" value="@stext" />
                    <button type="submit" class="btn btn-secondary">OK</button>
                </div>
            </div>
        </div>


    </form>
    <table class="table">
        <tr>
 
            <th>รหัสร้านอาหาร</th>
            <th>ชื่อร้านอาหาร</th>
            <th>รายละเอียด</th>

        </tr>

        @{
            //กำหนดค่าเพื่อให้นับค่าแสดงลำดับ
            var i = 0;
        }
        @foreach (var item in Model)
        {
            i++;
            //Razor page ใข้เครื่องหมาย @ หน้าตัวแปรที่ต้องการให้แสดงผล
            <tr>

                <td>@item.ResId</td>
                <td>@item.ResName</td>
                <td>@item.ResDtl</td>

                
                <td>
                    <a asp-action="EditRestaurant" asp-route-id="@item.ResId">Edit</a>
                </td>
                <td class="text-center">
                    <a asp-action="Delete" asp-route-id="@item.ResId">Delete</a>
                </td>
            </tr>

        }
    </table>
</div>

Buffet/Views/Restaurant/Total.cshtml
@model IEnumerable<Buffet.ViewModels.Pmvm>


<img src="/Icon/copper header.png" class="d-block w-100" alt="...">
@foreach (var item in Model)
{
                        <h1 class="text-center" pt-5 my-5>@item.ResName</h1>
                        <h4 class="text-center" pt-5 my-5>@item.ResDtl</h4>
}
<div class="container mx-5 my-5">
    <h3>สรุปยอดชำระ</h3>
</div>
<div class="container" style="background-color : pink">
    <div class="container mt-5">
        <div class="row">
            @foreach (var item in Model)
            {
                                <div class="col-md-3">
                                    <h3 class="font-weight-bold my-5">@item.CourseName</h3>

                                </div>
                                <div class="col-md-5">
                                    <p class="text-center">@item.CourseDtl</p>
                                </div>
                                <div class="col text-right col-lg-3">
                                        <p class="font-weight-bold">@item.CoursePrice NET price per person</p>
                                </div>
            }
            <div class="col-md-3">
                <h3 class="font-weight-bold my-5">Copper Set 1</h3>

            </div>
            <div class="col-md-5">
                <p class="text-center">International Buffet + Select 1 Premium Dish from 3 Options</p>
            </div>
            <div class="col text-right col-lg-3">
                <p class="font-weight-bold">฿1,999</p>
                <p>NET price per person</p>
                <h5 class="mt-5">รอบ วันจันทร์ที่ 18 มีนาคม 2024</h5>
                <p>เวลา 13.00-15.00</p>
            </div>
            <hr class="mx-n3">
            <h3>Making money method</h3>
            @* qrcode_payment 
            <div class="row">
                <div class="col">
                    <h1 class="pt-2">Thai Qr Payment</h1>
                </div>
                <div class="col">
                    <img src="" class="d-block w-100 my-5" alt="...">
                </div>
            </div>*@

            <hr class="mx-n3"> 
            @* credit card *@
            <form asp-controller="Restaurant" asp-action="Payment" method="post">
                <div class="row">
                    <div class="col">
                        <h1 class="pt-2">Credit/Debit Card</h1>
                    </div>
                    <div class="col">

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">
                                <h6 class="mb-0"></h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <select class="form-select" name="method" id="method"> @*Method*@
                                    <option value="Visa">Visa</option>
                                    <option value="Mastercard">Mastercard</option>
                                </select>
                            </div>
                        </div>

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">
                                <h6 class="mb-0">รหัสบัตร</h6>

                            </div>
                            <div class="col-md-9 pe-5">

                                <input type="text" name = "Cardnum" class="form-control form-control-lg" maxlength="16" />   @*Card number*@
                            </div>
                        </div>
                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">
                                <h6 class="mb-0">วันหมดอายุ</h6>
                            </div>
                            <div class="col-md-9 pe-5">
                                <!-- <input type="month" id="start" name="start" min="2010-03" value="2024-3" /> -->
                                <input type="text" name="Exp" class="form-control form-control-lg" maxlength="5" /> @*Expiration*@

                            </div>
                        </div>
                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">
                                <h6 class="mb-0">CCV</h6>

                            </div>
                            <div class="col-md-9 pe-5">
                                <input type="text" name="ccv" class="form-control form-control-lg" maxlength="3" />         @*CCV*@
                            </div>
                        </div>
                    </div>
                </div>
                <hr class="mx-n3">
                @* policy *@
                <a asp-area="" asp-controller="Home" asp-action="Privacy" class="my-3">ข้อกำหนดและเงื่อนไข</a>
                <hr class="mx-n3">
                @* สรุปยอด *@
                <div class="row">
                    <div class="col">
                        <h3>รวมทั้งหมด</h3>
                    </div>
                    <div class="col">
                        <h3 class="text-end">1999 บาท</h3>
                    </div>
                    <div class="px-5 py-4 text-center">
                        <button type="submit" class="btn btn-primary btn-lg">ยืนยัน</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

Buffet/Views/Restaurant/TypeList.cshtml
@model IEnumerable<Buffet.ViewModels.Pdvm>
@{
    var stext = ViewBag.theText;
}
@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.ErrorMesage;
    </div>
}

<div class="container pt-5 mt-5">
    <div class="row">
        <div class="col-sm-6 col-md-8 col-lg-9">
            <a class="btn btn-primary" asp-action="Index">
                <i class=""></i>Restaurant
            </a>
            <a class="btn btn-primary" asp-action="CourseList">
                <i class=""></i>Course
            </a>
            <a class="btn btn-primary" asp-action="SetList">
                <i class=""></i>Set
            </a>
            <a class="btn btn-primary" asp-action="TypeList">
                <i class=""></i>Type
            </a>
        </div>
    </div>
</div>
<div class="container pt-3 mt-5">
    <form asp-controller="Restaurant" asp-action="Index">
        <div class="row">
            <div class="col-sm-6 col-md-8 col-lg-9">
                <a class="btn btn-primary" asp-action="Create">
                    <i class="bg-info bi-plus-lg"></i>เพิ่มร้านอาหาร
                </a>
                <a class="btn btn-primary" asp-action="CreateCourse">
                    <i class="bg-info bi-plus-lg"></i>เพิ่มCourse
                </a>
                <a class="btn btn-primary" asp-action="CreateTablesets">
                    <i class="bg-info bi-plus-lg"></i>เพิ่มชุดโต๊ะ
                </a>
                <a class="btn btn-primary" asp-action="CreateResType">
                    <i class="bg-info bi-plus-lg"></i>เพิ่มประเภทของร้าน
                </a>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="input-group">
                    <span class="input-group-text">ค้นหา</span>
                    <input type="text" name="stext" class="form-control" value="@stext" />
                    <button type="submit" class="btn btn-secondary">OK</button>
                </div>
            </div>
        </div>


    </form>
    <table class="table">
        <tr>

            <th>รหัสประเภทร้านอาหาร</th>
            <th>ชื่อประเภท</th>

        </tr>

        @{
            //กำหนดค่าเพื่อให้นับค่าแสดงลำดับ
            var i = 0;
        }
        @foreach (var item in Model)
        {
            i++;
            //Razor page ใข้เครื่องหมาย @ หน้าตัวแปรที่ต้องการให้แสดงผล
            <tr>

                <td>@item.TypeId</td>
                <td>@item.TypeName</td>
                <td>
                    <a asp-action="EditResType" asp-route-id="@item.TypeId">Edit</a>
                </td>
                <td class="text-center">
                    <a asp-action="DeletePostsType" asp-route-id="@item.TypeId">Delete</a>
                </td>
            </tr>
        }
    </table>
</div>