Buffet/Controllers/ReportController.cs
using Buffet.Controllers;
using Buffet.Models;
using Buffet.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using System.Runtime.Intrinsics.X86;

namespace Buffet.Controllers
{
    public class ReportController : Controller
    {
        readonly BuffetContext _db;
        public ReportController(BuffetContext db) { _db = db; }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("DutyId") != "admin" && HttpContext.Session.GetString("DutyId") != "staff")
            {
                TempData["ErrorMessage"] = "ไม่มีสิทธิใช้งาน";
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public IActionResult SaleDaily()
        {
            if (HttpContext.Session.GetString("DutyId") != "admin" && HttpContext.Session.GetString("DutyId") != "staff")
            {
                TempData["ErrorMessage"] = "ไม่มีสิทธิใช้งาน";
                return RedirectToAction("Index", "Home");
            }
            DateTime thedate = DateTime.Today;
            DateTime endDate = thedate.AddDays(1).Date;
            var rep = from cd in _db.Books
                      join c in _db.Courses on cd.CourseId equals c.CourseId into join_c
                      from t_c in join_c
                      join r in _db.Restaurants on cd.ResId equals r.ResId into join_r
                      from t_r in join_r
                      join p in _db.Payments on cd.BookId equals p.BookId into join_p
                      from t_p in join_p.DefaultIfEmpty() // เปลี่ยนจาก join ให้เป็น left join
                      where cd.SelectDate >= thedate && cd.SelectDate <= endDate
                      group new { cd, t_r } by new { t_r.ResId, t_r.ResName, t_c.CoursePrice } into g
                      select new RepBook
                      {
                          CoursePrice = g.Key.CoursePrice,
                          ResId = g.Key.ResId,
                          ResName = g.Key.ResName,
                          TotalBookings = g.Sum(x => x.cd.CourseId) // จำนวนรายการที่จองทั้งหมดสำหรับแต่ละกลุ่ม
                                                                    // จำนวนรายการที่จองทั้งหมดสำหรับแต่ละกลุ่ม
                      };

            ViewBag.theDate = thedate.ToString("yyyy/MM/dd HH:mm:ss");
            ViewBag.TotalBookings = rep.Sum(item => item.TotalBookings);
            return View(rep);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaleDaily(DateTime thedate)
        {
            if (HttpContext.Session.GetString("DutyId") != "admin" && HttpContext.Session.GetString("DutyId") != "staff")
            {
                TempData["ErrorMessage"] = "ไม่มีสิทธิใช้งาน";
                return RedirectToAction("Index", "Home");
            }
            DateTime endDate = thedate.AddDays(1).Date;

            var rep = from cd in _db.Books
                      join c in _db.Courses on cd.CourseId equals c.CourseId into join_c
                      from t_c in join_c
                      join r in _db.Restaurants on cd.ResId equals r.ResId into join_r
                      from t_r in join_r
                      join p in _db.Payments on cd.BookId equals p.BookId into join_p
                      from t_p in join_p.DefaultIfEmpty() // เปลี่ยนจาก join ให้เป็น left join
                      where cd.SelectDate >= thedate && cd.SelectDate <= endDate
                      group new { cd, t_r } by new { t_r.ResId, t_r.ResName, t_c.CoursePrice } into g
                      select new RepBook
                      {
                          CoursePrice = g.Key.CoursePrice,
                          ResId = g.Key.ResId,
                          ResName = g.Key.ResName,
                          TotalBookings = g.Sum(x => x.cd.CourseId) // จำนวนรายการที่จองทั้งหมดสำหรับแต่ละกลุ่ม
                                                                    // จำนวนรายการที่จองทั้งหมดสำหรับแต่ละกลุ่ม
                      };
            ViewBag.theDate = thedate.ToString("yyyy/MM/dd HH:mm:ss");
            ViewBag.TotalBookings = rep.Sum(item => item.TotalBookings);
            return View(rep);

        }

        public IActionResult SaleMonthly()
        {
            if (HttpContext.Session.GetString("DutyId") != "admin" && HttpContext.Session.GetString("DutyId") != "staff")
            {
                TempData["ErrorMessage"] = "ไม่มีสิทธิใช้งาน";
                return RedirectToAction("Index", "Home");
            }
            //กำหนดวันแรก และคำนวณหาวันสุดท้ายของเดือนปัจจุบัน
            var theMonth = DateTime.Now.Month;
            var theYear = DateTime.Now.Year;
            //วันแรกคือวันที่ 1 ของเดือน
            DateTime sDate = new DateTime(theYear, theMonth, 1);
            //วันสุดท้ายคือวันที 1 ของเดือนหน้า ลบไป1วัน
            DateTime eDate = new DateTime(theYear, theMonth, 1).AddMonths(1).AddDays(-1);

            var rep = from cd in _db.Books
                      join c in _db.Courses on cd.CourseId equals c.CourseId into join_c
                      from t_c in join_c
                      join r in _db.Restaurants on cd.ResId equals r.ResId into join_r
                      from t_r in join_r
                      join p in _db.Payments on cd.BookId equals p.BookId into join_p
                      from t_p in join_p.DefaultIfEmpty() // เปลี่ยนจาก join ให้เป็น left join
                      where cd.SelectDate >= sDate && cd.SelectDate <= eDate
                      group new { cd, t_r } by new { t_r.ResId, t_r.ResName , t_c.CoursePrice } into g
                      select new RepBook
                      {
                          CoursePrice = g.Key.CoursePrice,
                          ResId = g.Key.ResId,
                          ResName = g.Key.ResName,
                          TotalBookings = g.Sum(x => x.cd.CourseId) // จำนวนรายการที่จองทั้งหมดสำหรับแต่ละกลุ่ม
                                                                    // จำนวนรายการที่จองทั้งหมดสำหรับแต่ละกลุ่ม
                      };
            ViewBag.sDate = sDate.ToString("yyyy-MM-dd HH:mm:ss");
            ViewBag.eDate = eDate.ToString("yyyy-MM-dd");

            return View(rep);


        }
       [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaleMonthly(DateTime sDate, DateTime eDate)
        {
            if (HttpContext.Session.GetString("DutyId") != "admin" && HttpContext.Session.GetString("DutyId") != "staff")
            {
                TempData["ErrorMessage"] = "ไม่มีสิทธิใช้งาน";
                return RedirectToAction("Index", "Home");
            }
            var rep = from cd in _db.Books
                      join c in _db.Courses on cd.CourseId equals c.CourseId into join_c
                      from t_c in join_c
                      join r in _db.Restaurants on cd.ResId equals r.ResId into join_r
                      from t_r in join_r
                      join p in _db.Payments on cd.BookId equals p.BookId into join_p
                      from t_p in join_p.DefaultIfEmpty() // เปลี่ยนจาก join ให้เป็น left join
                      where cd.SelectDate >= sDate && cd.SelectDate <= eDate
                      group new { cd, t_r } by new { t_r.ResId, t_r.ResName, t_c.CoursePrice } into g
                      select new RepBook
                      {
                          CoursePrice = g.Key.CoursePrice,
                          ResId = g.Key.ResId,
                          ResName = g.Key.ResName,
                          TotalBookings = g.Sum(x => x.cd.CourseId) // จำนวนรายการที่จองทั้งหมดสำหรับแต่ละกลุ่ม
                                                                    // จำนวนรายการที่จองทั้งหมดสำหรับแต่ละกลุ่ม
                      };
            ViewBag.sDate = sDate.ToString("yyyy-MM-dd HH:mm:ss");
            ViewBag.eDate = eDate.ToString("yyyy-MM-dd HH:mm:ss");
            return View(rep);

        }


    }


}

Buffet/Controllers/StaffController.cs
using Microsoft.AspNetCore.Mvc;
using Buffet.Models;

namespace Buffet.Controllers
{
    public class StaffController : Controller
    {
        public readonly BuffetContext _db;

        public StaffController(BuffetContext db) { _db = db; }


        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("StfId") == null)
            {
                return RedirectToAction("Login");
            }
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index","Home");
        }


        public IActionResult Login()
        {
            return View();
        }
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(string userName, string userPass)
        {
            //Query หาว่ามี Login Password ที่ระบุหรือไม่
            var stf = from s in _db.Staffs
                      where s.StaffName.Equals(userName)
                          && s.StaffPass.Equals(userPass)
                      select s;
            //ถ้าข้อมูลเท่ากับ 0 ให้บอกว่าหาข้อมูลไม่พบ
            if (stf.Count() == 0)
            {
                TempData["ErrorMessage"] = "ระบุผู้ใช้หรือรหัสผ่านไม่ถูกต้อง";
                return View();
            }
            //ถ้าหาข้อมูลพบ ให้เก็บค่าเข้า Session
            string StfId;
            string StfName;
            string DutyId;
            foreach (var item in stf)
            {
                //อ่านค่าจาก Object เข้าตัวแปร
                StfId = item.StaffId;
                StfName = item.StaffName;
                DutyId = item.DutyId;
                //เอาค่าจากตัวแปรเข้า Session
                HttpContext.Session.SetString("StfId", StfId);
                HttpContext.Session.SetString("StfName", StfName);
                HttpContext.Session.SetString("DutyId", DutyId);
            }
            //ทำการย้ายไปหน้าที่ต้องการ
            return RedirectToAction("Index", "Restaurant");
        }




    }
}

Buffet/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;
@{
    var CusId = HttpContextAccessor.HttpContext.Session.GetString("CusId");
    var CusName = HttpContextAccessor.HttpContext.Session.GetString("CusName");
    var CartId = HttpContextAccessor.HttpContext.Session.GetString("CartId");
    var resid = HttpContextAccessor.HttpContext.Session.GetString("ResId");
    var CartMoney = HttpContextAccessor.HttpContext.Session.GetString("CartMoney");
    var CartQty = HttpContextAccessor.HttpContext.Session.GetString("CartQty");
    var StfId = HttpContextAccessor.HttpContext.Session.GetString("StfId");

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Buffet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Buffet.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="/css/Booking/bootstrap.min.css">
    <link rel="stylesheet" href="/css/Booking/font-awesome.min.css">
    <link rel="stylesheet" href="/css/Booking/owl.carousel.min.css">
    <link rel="stylesheet" href="/css/Booking/style.css">
    <link rel="stylesheet" href="~/css/payment.css">
    <link rel="stylesheet" href="~/css/jquery.datetimepicker.min.css" />


</head>
<body>
    <header>

        <nav class="fixed-top navbar navbar-dark navbar-expand-sm navbar-toggleable-sm text-white " style="background-color: #FB054F;">
            <div class="container">
                @if (StfId != null)
                {
                    <a class="navbar-brand " asp-area="" asp-controller="Staff" asp-action="Index">
                        <img src="/Icon/icon.png" alt="" width="50" height="50">
                    </a>
                }
                else
                {
                    <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="/Icon/icon.png" alt="" width="50" height="50">
                    </a>
                }

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <ul class="navbar-nav flex-grow-1">
                    <div class="navbar-collapse collapse d-sm-inline-flex ">
                        @if (StfId == null)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        }
                        else
                        {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Restaurant" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                รายงาน
                            </a>
                            <ul class="dropdown-menu bg-dark">
                                <li>
                                    <a class="dropdown-item" asp-controller="Report" asp-action="SaleDaily">
                                        สินค้าขายรายวัน
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Report" asp-action="SaleMonthly">
                                        สินค้าขายรายเดือน
                                    </a>
                                </li>


                            </ul>
                        </li>
                        }

                </ul>

            </div>


            <ul class="navbar-nav ">
                @if (CusId != null)
                {
                    <li class="nav-item">
                        <button type="button" class="btn btn-light me-2">
                            <a class="nav-link text-dark" asp-controller="Customer" asp-action="Show" asp-route-id="@CusId">
                                @CusName
                            </a>
                        </button>
                    </li>
                    <li class="nav-item">
                        <button type="button" class="btn btn-light me-2">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </button>
                    </li>
                }
                else
                {
                    if (StfId == null)
                    {
                        <li class="nav-item">
                            <button type="button" class="btn btn-light me-2">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Register">Register</a>
                            </button>
                        </li>
                        <li class="nav-item">
                            <button type="button" class="btn btn-light me-2">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Login">Login</a>
                            </button>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <button type="button" class="btn btn-primary me-2">
                                <a class="nav-link text-white" asp-controller="Staff" asp-action="Logout">Logout</a>
                            </button>
                        </li>
                    }

                }


            </ul>
            </div>
            </div>
        </nav>

    </header>
    <div class="">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <style>
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            padding: 0px;
            height: 20px;
        }
    </style>
    <footer class="footer">
        <div class="container-fluid text-white" style="font-family:'Poppins',sans-serif;background: #FB054F;background:linear-gradient(to right#ff82a7,#f7a3bc,#FB054F);">
            <div class="row justify-content-around text-md-start">
                <div class="col-md-1 text-center">
                    <div class="row gallery">
                        <h class="fw-bold mt-5 fs-1 ms-5">BUFTERAUNT</h>
                    </div>

                </div>

                <div class="col-md-2">
                    <li class="fw-bold list-unstyled mt-4">Follow us</li>
                    <ul class="list-unstyled d-flex justify-content-center justify-content-md-start">
                        <li><a href="#" class="text-white"><i class="fa-brands fa-facebook me-2 fa-2x"></i></a></li>
                        <li><a href="#" class="text-white"><i class="fa-brands fa-whatsapp me-2 fa-2x"></i></a></li>
                        <li><a href="#" class="text-white"><i class="fa-brands fa-youtube me-2 fa-2x"></i></a></li>
                        <li><a href="#" class="text-white"><i class="fa-brands fa-instagram me-2 fa-2x"></i></a></li>
                    </ul>
                </div>

                <div class="row">
                    <div class="col-md- text-center pt-1">
                        <p>&copy; 2024 - Buffet <a href="#" class="text-white">Terms & Conditions</a></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    </div>

    <script src="/js/Booking/jquery-3.3.1.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="/js/Booking/main.js"></script>
    <script src="~/js/jquery.datetimepicker.full.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>