Buffet/Models/Payment.cs
using System;
using System.Collections.Generic;

namespace Buffet.Models;

public partial class Payment
{
    public string PayId { get; set; } = null!;

    public string CardId { get; set; } = null!;

    public string CardExpire { get; set; } = null!;

    public string CcvNum { get; set; } = null!;

    public string PayType { get; set; } = null!;

    public string BookId { get; set; } = null!;
}

Buffet/Controllers/HomeController.cs
using Buffet.Models;
using Buffet.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;


namespace Buffet.Controllers
{
    public class HomeController : Controller
    {
        private readonly BuffetContext _db;

        public HomeController(BuffetContext db)
        {
            _db = db;
        }

        public IActionResult Search(string search)
        {
            var pdvm = (from p in _db.Restaurants
                        join pt in _db.Courses on p.ResId equals pt.ResId into join_p_pt
                        from p_pt in join_p_pt
                        where p.ResName.Contains(search) || p_pt.CourseName.Contains(search) || p_pt.CourseType.Contains(search)
                        select new Pdvm
                        {
                            ResId = p.ResId,
                            ResName = p.ResName,
                            ResPhone = p.ResPhone,
                            ResImg = p.ResImg,
                            ResAvg = p.ResAvg,
                            ResLocation = p.ResLocation,
                            ResDtl = p.ResDtl,
                            CourseId = p_pt.CourseId,
                            CourseName = p_pt.CourseName,
                            CoursePrice = p_pt.CoursePrice,
                            CourseDtl = p_pt.CourseDtl,
                            CourseImg = p_pt.CourseImg,
                            CourseType = p_pt.CourseType
                        }).GroupBy(x => new { x.ResId, x.CourseId,x.ResName,x.CourseType }).Select(g => g.First()); // ใช้ GroupBy เพื่อแบ่งข้อมูลออกเป็นกลุ่มและเลือกข้อมูลแต่ละกลุ่ม
            if (pdvm == null) return NotFound();
            ViewData["Search"] = search;
            return View(pdvm);
        }
        public IActionResult Index()
        {
            var shop = from i in _db.Restaurants

                       select new Pdvm
                       {
                           ResId = i.ResId,
                           ResName = i.ResName,
                           ResPhone = i.ResPhone,
                           ResImg = i.ResImg,
                           ResAvg = i.ResAvg,
                           ResLocation = i.ResLocation,
                           ResDtl = i.ResDtl
                       };
            if (shop == null) return NotFound();
            ViewBag.ErrorMessage = TempData["ErrorMessage"];
            
            return View(shop);
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(Customer obj)
        {
            try
            {
                    var cusIdCount = (from id in _db.Customers select id).Count();
                    obj.CusId = "C" + 00 + cusIdCount;
                    _db.Customers.Add(obj);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View(obj);
            }
            ViewBag.ErrorMessage = "การบันทึกผิดพลาด";
            return RedirectToAction("Index");
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(string userName, string userPass)
        {
            var cus = from c in _db.Customers
                      where c.CusEmail.Equals(userName) && c.CusPass.Equals(userPass)
                      select c;

            if (cus.ToList().Count() == 0)
            {
                TempData["ErrorMessage"] = "ไม่พบข้อมูล";
                return RedirectToAction("Login");
            }

            string CusId;
            string CusName;

            foreach (var item in cus)
            {
                CusId = item.CusId.ToString();
                CusName = item.CusName;

                HttpContext.Session.SetString("CusId", CusId);
                HttpContext.Session.SetString("CusName", CusName);
                //var theRecord = _db.Customers.Find(CusId);
                //theRecord.LastLogin = DateOnly.FromDateTime(DateTime.Now);

                //_db.Entry(theRecord).State = EntityState.Modified;
            }

            //_db.SaveChanges();
            return RedirectToAction("index");
        }
        

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }
        /*
        public IActionResult Store(string id)
        {
            

            if (id == null)
            {
                TempData["ErrorMessage"] = "ระบุ ID";
                return RedirectToAction("Index");
            }
            var obj = _db.Restaurants.Find(id);
            if (obj == null)
            {
                TempData["ErrorMessage"] = "ไม่พบ ID";
                return RedirectToAction("Index");
            }
            var shop = from i in _db.Restaurants where i.ResId.Equals(id) 
                       select new Pdvm
                       {
                           ResId = i.ResId,
                           ResName = i.ResName,
                           
                           ResPhone = i.ResPhone,
                           ResAvg   = i.ResAvg,
                           ResLocation  = i.ResLocation
                       };
            return View(shop);
        }
        */

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Buffet/Controllers/ReserveController.cs
using Microsoft.AspNetCore.Http;
using Buffet.Models;
using Buffet.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using System;
using System.Diagnostics;
using System.Net;
using System.Net.NetworkInformation;
using System.Reflection.Metadata;


namespace Buffet.Controllers
{
    public class ReserveController : Controller
    {
        private readonly BuffetContext _db;

        public ReserveController(BuffetContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Payment(int id)
        {
            if (id == null)
            {
                TempData["ErrorMessage"] = "ระบุ ID";
                return RedirectToAction("Index");
            }
            var obj = _db.Courses.Find(id);
            if (obj == null)
            {
                TempData["ErrorMessage"] = "ไม่พบ ID";
                return RedirectToAction("Index");
            }
            var ids = id.ToString();
            HttpContext.Session.SetString("CourseId", ids);
            var shop = from i in _db.Courses
                       where i.ResId.Equals(id)
                       join c in _db.Restaurants on i.ResId equals c.ResId into join_c
                       from i_c in join_c

                       select new Pdvm
                       {
                           CourseId = i.CourseId,
                           CourseName = i.CourseName,
                           CoursePrice = i.CoursePrice,
                           CourseDtl = i.CourseDtl,
                           CourseImg = i.CourseImg,
                           CourseType = i.CourseType
                       };

            return View(shop);
        }

        public IActionResult Booking(string id)
        {
            if(HttpContext.Session.GetString("CusId") == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                TempData["ErrorMessage"] = "ระบุ ID";
                return RedirectToAction("Index");
            }
            var obj = _db.Restaurants.Find(id);
            if (obj == null)
            {
                TempData["ErrorMessage"] = "ไม่พบ ID";
                return RedirectToAction("Index");
            }
            HttpContext.Session.SetString("ResId", id);

            var shop = from i in _db.Courses where i.ResId.Equals(id)

                       join c in _db.Restaurants on i.ResId equals c.ResId into join_c
                       from i_c in join_c

                       select new Pdvm
                       {
                           ResId = i_c.ResId,
                           ResName = i_c.ResName,
                           ResPhone = i_c.ResPhone,
                           ResAvg = i_c.ResAvg,
                           ResImg = i_c.ResImg,
                           ResLocation = i_c.ResLocation,
                           ResDtl = i_c.ResDtl,
                           CourseId = i.CourseId,
                           CourseName = i.CourseName,
                           CoursePrice = i.CoursePrice,
                           CourseDtl = i.CourseDtl,
                           CourseImg = i.CourseImg,
                           CourseType = i.CourseType
                        };
               
                return View(shop);
        }

       /* public IActionResult Book(string id)
        {
            if (id == null)
            {
                TempData["ErrorMessage"] = "ระบุ ID";
                return RedirectToAction("Index");
            }
            var x = Int32.Parse(id);
            var obj = _db.Courses.Find(x);
            if (obj == null)
            {
                TempData["ErrorMessage"] = "ไม่พบ ID";
                return RedirectToAction("Index");
            }
            if (HttpContext.Session.GetString("CusId") == null)
            {
                TempData["ErrorMessage"] = "กรุณาล็อกอิน";
                return RedirectToAction("Login", "Home");
            }
            HttpContext.Session.SetString("Course", id);

            DateTime theDate = DateTime.Now.Date;
            var rep = from b in _db.Books

                      join co in _db.Courses on b.CourseId equals co.CourseId into join_co
                      from b_co in join_co

                      join t in _db.Tables on b.TableId equals t.TableId into join_t
                      from b_t in join_t

                      select new Book
                      {
                          BookId = b.BookId,
                          ResId = b.ResId,
                          CourseId = b.CourseId,
                          TableId = b.TableId,
                      };
            // return View(rep);
            ViewData["Crs"] = new SelectList(_db.Courses, "CourseId", "CourseName");
            return View(rep);

        }*/

        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Book(Book obj)
        {
            
            obj.SelectDate = DateTime.Now;
            var bookIdCount = (from id in _db.Books select id).Count();
            obj.BookId = "B" + 00 + bookIdCount;
            var tableUpdate = _db.Tablesets.FirstOrDefault();
            if (obj.BookSeat <= 4)
            {
                obj.TableId = "S";
                tableUpdate.Ssize -= 1;
            }
            else if (obj.BookSeat <= 6)
            {
                obj.TableId = "M";
                tableUpdate.Msize -= 1;
            }
            else if (obj.BookSeat <= 10 && obj.BookSeat > 6)
            {
                obj.TableId = "L";
                tableUpdate.Lsize -= 1;
            }

            _db.SaveChanges();
            return RedirectToAction("Total");

        }*/
        public IActionResult Total()
        {
            var ids = HttpContext.Session.GetString("ResId");

             var Total = from t in _db.Books
                         where t.ResId.Equals(ids)

                         join c in _db.Courses on t.CourseId equals c.CourseId into join_c
                          from t_c in join_c


                         join r in _db.Restaurants on t.ResId equals r.ResId into join_r
                         from t_r in join_r


                         join p in _db.Payments on t.BookId equals p.BookId into join_p
                         from t_p in join_p

                    select new Pmvm
                         {
                             ResId = t.ResId,
                             ResName = t_r.ResName,
                             ResDtl = t_r.ResDtl,
                           /* CourseName = t_c.CourseName,
                             CoursePrice = t_c.CoursePrice,
                             CourseDtl = t_c.CourseDtl,
                             CourseType = t_c.CourseType*/

                         };
            

            if (Total == null)
            {
                return NotFound();
            }


            return View(Total);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Payment(string method, string cardnumber, string exp,string ccv,DateTime date,int people) 
        {
            var Ccusid = HttpContext.Session.GetString("CusId");
            var coid = HttpContext.Session.GetString("CourseId");
            var Course = Convert.ToInt32(coid);
            var ids = HttpContext.Session.GetString("ResId");
            var time = DateTime.Now;
            //payment method
            var PayIdCount = (from pay in _db.Payments select pay).Count();
            var PayId = "P" + 00 + PayIdCount;
            var BookIdCount = (from bookid in _db.Books select bookid).Count();
            var BookId = "B" + 00 + PayIdCount;
            
            Payment pays = new Payment() { PayId = PayId,CardId  = cardnumber, CardExpire = exp, CcvNum = ccv, PayType  = method, BookId = BookId };
            Book Books = new Book()
            {
                BookId = BookId,
                CusId = Ccusid,
                ResId = ids,
                CourseId = Course
                , BookDate = date, BookStatus = "1",  BookSeat = people, SelectDate = time };

            _db.Payments.Add(pays);
     
            _db.Books.Add(Books);
            _db.SaveChanges();


            //books
            return RedirectToAction("Index","Home");
        }

        public IActionResult Nothing()
        {
            return View();
        }

    }
}

Buffet/Views/Home/Login.cshtml
@using Microsoft.AspNetCore.Http;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor;

@{
    ViewData["Title"] = "Login";
}

<div class="pt-5 mt-5"></div>
<div class="container justify-content-center align -items-center">
<div class="text-center">
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
        }

        @if (HttpContextAccessor.HttpContext.Session.GetString("CusId") == null)
    {
        <form asp-controller="Home" asp-action="Login" method="post">
        <div class=" row justify-content-center m-3">
            <div class="col-lg-4">
                <div class="input-group">
                    <div class="input-group-text"><i class="bi bi-person-circle"></i></div> 
                    <input type="text" name="userName" class="form-control" required />
                </div>
            </div>
        </div>
        <div class=" row justify-content-center m-3">
            <div class="col-lg-4">
                <div class="input-group">
                    <div class="input-group-text"><i class="bi bi-unlock-fill"></i></div>
                    <input type="password" name="userPass" class="form-control" required />
                </div>
            </div>
        </div>
        <div class=" row justify-content-center m-3">
            <div class="col-lg-2">
                <button type="submit" class="btn btn-primary">Login</button>
            </div>
        </div>
    </form>
        }
        else
        {
            <div class="display-3">Welcome @HttpContextAccessor.HttpContext.Session.GetString("CusName")</div>
            <h1 >Please go to <a asp-action="Index" asp-controller="Home">Home</a> to Booking Restaurants</h1>
        }
</div>
</div>

Buffet/Views/Home/Register.cshtml
@model Buffet.Models.Customer

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="CusId" class="control-label" ></label>
                <input asp-for="CusId" class="form-control" value="0"/>
                <span asp-validation-for="CusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CusName" class="control-label"></label>
                <input asp-for="CusName" class="form-control" />
                <span asp-validation-for="CusName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CusPass" class="control-label"></label>
                <input asp-for="CusPass" class="form-control" />
                <span asp-validation-for="CusPass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CusEmail" class="control-label"></label>
                <input asp-for="CusEmail" class="form-control" />
                <span asp-validation-for="CusEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CusPhone" class="control-label"></label>
                <input asp-for="CusPhone" class="form-control" />
                <span asp-validation-for="CusPhone" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Buffet/Views/Home/Search.cshtml
@model IEnumerable<Buffet.ViewModels.Pdvm>

@{
    ViewData["Title"] = "Search Page";
}

@{
    var stext = ViewBag.Search;
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Taviraj:300,400,500,600,700,800,900&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="/css/Booking/font-awesome.min.css">
    <link rel="stylesheet" href="/css/Booking/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/css/Home-Index.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <div class="">
        <div class="mt-3 pt-5"></div>
        <div class="slideshow-container">
            <div id="hero-carousel" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#hero-carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#hero-carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#hero-carousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active c-item fade-c-item">
                        <img src="/Icon/HomePage.jpg" class="d-block w-100 c-img" alt="...">
                    </div>
                    <div class="carousel-item c-item fade-c-item">
                        <img src="/Icon/background.png" class="d-block w-100 c-img" alt="...">
                    </div>
                    <div class="carousel-item c-item fade-c-item">
                        <img src="/Icon/background2.png" class="d-block w-100 c-img" alt="...">
                    </div>
                </div>
                <button class="carousel-control-prev prev" type="button" data-bs-target="#hero-carousel" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next next" type="button" data-bs-target="#hero-carousel" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>



        <div class="container">
            @* search *@
            <div class="container mt-5 mb-5 w-50">
                <form asp-action="Search" class="d-flex">
                    <input name="search" class="form-control me-2" type="search" placeholder="Search ....." value="@stext">
                    <button type="submit" class="btn btn-outline-info">Search</button>
                </form>
            </div>


           

            @* recomend *@
            <div class="container mx-5 mt-3">
            </div>
            @* card1 *@
            <section>
                <div class="testimonial-slider menu-slider">
                    <div id="recomend" class="carousel carousel-dark" data-bs-ride="carousel">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="testimonial-title menu-title">
                                        <i class="bi bi-quote display-2"></i>
                                        <h2 class="fw-bold display-6 text-black">"Menu Recomend"</h2>
                                    </div>
                                    <button class="carousel-control-prev prev-icon" type="button" data-bs-target="#recomend" data-bs-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="visually-hidden">Previous</span>
                                    </button>
                                    <button class="carousel-control-next next-icon" type="button" data-bs-target="#recomend" data-bs-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="visually-hidden">Next</span>
                                    </button>
                                </div>
                                <div class="col-md-8">
                                    <div class="carousel-inner menu-inner">
                                        @foreach (var i in Model)
                                        {
                                            <div class="carousel-item active menu-item">
                                                <div class="card ">
                                                    <div class="img-wrapper"><a asp-controller="Reserve" asp-action="Booking" asp-route-id="@i.ResId"> <img src="/imgres/@i.ResImg" class="d-block w-100"></a> </div>
                                                    <div class="card-body">
                                                        <h5 class="card-title"><a class="text-decoration-none" asp-controller="Reserve" asp-action="Booking" asp-route-id="@i.ResId">@i.ResName</a></h5>
                                                        <p class="card-text">@i.ResDtl</p>
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

           
            <div class="mb-5"></div>


        </div>
    </div>
        

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="/js/Booking/jquery-3.3.1.min.js"></script>
    <script src="/js/Booking/main.js"></script>
    <script src="/js/site.js"></script>
</body>
</html>

Buffet/Views/Home/SignUp.cshtml
@model Buffet.Models.Customer

@{
	ViewData["Title"] = "SignUp";
}
<head>
	<meta charset="utf-8"></meta>
</head>
<body>
	<form asp-action="SignUp">
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		<section class="vh-100" style="">
		<div class="container h-100">
			<div class="row d-flex justify-content-center align-items-center h-100">
				<div class="col-xl-9">
					<h1>Sign Up</h1>
					<h1 class="text-white mb-4">Apply for a job</h1>

					<div class="card" style="border-radius: 15px;">
						<div class="card-body">
							<div class="row align-items-center py-3">
								<div class="col-md-3 ps-5">
									<h6 class="mb-0">Email address</h6>

								</div>
								<div class="col-md-9 pe-5">
									<label asp-for="CusEmail" class="control-label"></label>
									<input asp-for="CusEmail" class="form-control form-control-lg" placeholder="eee@example.com" />
									<span asp-validation-for="CusEmail" class="text-danger"></span>
								</div>
							</div>

							<hr class="mx-n3">

							<div class="row align-items-center py-3">
								<div class="col-md-3 ps-5">
									<h6 class="mb-0">Name</h6>

								</div>
								<div class="col-md-9 pe-5">
									<label asp-for="CusName" class="control-label"></label>
									<input asp-for="CusName" class="form-control form-control-lg" placeholder="john wick" />
									<span asp-validation-for="CusName" class="text-danger"></span>
								</div>
							</div>

							<hr class="mx-n3">
							<div class="row align-items-center py-3">
								<div class="col-md-3 ps-5">
									<h6 class="mb-0">Phone number</h6>

								</div>
								<div class="col-md-9 pe-5">
									<label asp-for="CusPhone" class="control-label"></label>
									<input asp-for="CusPhone" class="form-control form-control-lg" placeholder="0910766589" />
									<span asp-validation-for="CusPhone" class="text-danger"></span>
								</div>
							</div>

							<hr class="mx-n3">
							<div class="row align-items-center py-3">
								<div class="col-md-3 ps-5">
									<h6 class="mb-0">password</h6>

								</div>
								<div class="col-md-9 pe-5">
									<label asp-for="CusPass" class="control-label"></label>
									<input asp-for="CusPass" class="form-control form-control-lg" />
									<span asp-validation-for="CusPass" class="text-danger"></span>
								</div>
							</div>
							<hr class="mx-n3">

							<div class="px-5 py-4">
								<button type="submit" value="SignUp" class="btn btn-primary btn-lg">Sign up</button>
							</div>

						</div>
					</div>

				</div>
			</div>
		</div>
		</section>
	</form>

</body>